Для заданной матрицы размером 8 на 8 в которой K-я строка матрицы совпадает с
k-м столбцом. Найти сумму элементов в тех строках, которые содержат хотя бы один
отрицательный элемент.

In [5]:
import numpy as np

In [6]:
matrix = np.zeros((8, 8), int)
np.fill_diagonal(matrix, np.random.randint(-10, 20, size=8))
matrix = np.transpose(matrix)
print("Матрица:\n", matrix)

Матрица:
 [[ 14   0   0   0   0   0   0   0]
 [  0  -2   0   0   0   0   0   0]
 [  0   0  17   0   0   0   0   0]
 [  0   0   0   3   0   0   0   0]
 [  0   0   0   0 -10   0   0   0]
 [  0   0   0   0   0  -7   0   0]
 [  0   0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   0  13]]


In [7]:
neg_rows = np.where(np.any(matrix < 0, axis=1))[0]
neg_rows_sum = np.sum(matrix[neg_rows], axis=1).sum()
print("Сумма элементов в строках с отрицательными элементами:", neg_rows_sum)

Сумма элементов в строках с отрицательными элементами: -19
