Для заданной матрицы размером 8 на 8 в которой K-я строка матрицы совпадает с
k-м столбцом. Найти сумму элементов в тех строках, которые содержат хотя бы один
отрицательный элемент.

In [8]:
import numpy as np

In [9]:
n = 8
matrix = np.random.randint(-10, 20, (n, n))
k = int(input("введите K: "))
matrix[k-1,:] = matrix[:,k-1]
print("Матрица:\n", matrix)

введите K: 2
Матрица:
 [[ -3  -5   5   0  -2   7   0  12]
 [ -5   6  13   4  -7   7  13  -5]
 [  3  13   2   0  -1   0  16   0]
 [ 16   4  -6 -10   7  -5  10  13]
 [ -4  -7   1  -6  -5   1  -6  -7]
 [  8   7  -9  10  17   8   3  14]
 [  3  13   9  11  14  -1   3   3]
 [ -5  -5  -2   7  11  16   7   0]]


In [10]:
neg_rows = np.where(np.any(matrix < 0, axis=1))[0]
neg_rows_sum = np.sum(matrix[neg_rows], axis=1).sum()
print("Сумма элементов в строках с отрицательными элементами:", neg_rows_sum)

Сумма элементов в строках с отрицательными элементами: 211
